name: flutter_todo
description: Flutter Graphql Client

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  go_router: ^5.0.2
  graphql: ^5.1.2-beta.4
  graphql_codegen: ^0.11.1
  graphql_flutter: ^5.1.1-beta.4
  provider: ^6.0.3
  very_good_analysis: ^3.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
