name: flutter_todo
description: Flutter Graphql Client Example

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  graphql: ^5.1.2-beta.4
  graphql_flutter: ^5.1.1-beta.4

dev_dependencies:
  build_runner: ^2.3.0

  flutter_test:
    sdk: flutter
  graphql_codegen: ^0.11.2
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
